services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ventacafe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - venta-cafe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ventacafe"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - venta-cafe-network
    depends_on:
      - db

  venta-cafe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: venta-cafe-api
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/ventacafe
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
    networks:
      - venta-cafe-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  venta-cafe-network:
    driver: bridge
